#!/bin/bash

IMAGE="savedcont"
USER="peter"
SERVER="192.168.10.200"

p=`pwd`
cd ..

n=`pwd | awk 'BEGIN {FS="/"};{printf $NF }'`

if [ -f $IMAGE ]; then
    d=`date +"%Y%m%d%H%M%S"`
    IMAGE=`echo "$IMAGE$d" `
fi

sudo podman export -o "$IMAGE" $n
scp "$IMAGE" "$USER"@"$SERVER":/home/"$USER"

cd $p

#
