FROM debian

MAINTAINER peter version: 0.1

RUN apt-get update

#RUN sudo DEBIAN_FRONTEND=noninteractive aptitude install -y -q chef

# System
RUN apt-get install -y mc
RUN apt-get install -y aptitude

# Postfix
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y postfix
RUN apt-get install -y procmail

# Dovecot
RUN apt-get install -y dovecot-core
RUN apt-get install -y dovecot-imapd

# Clamav
RUN apt-get install -y clamav
RUN apt-get install -y clamav-daemon
#RUN apt-get install -y clamsmtp

# Amavis
RUN apt-get install -y amavisd-new

# Spamassassin
RUN apt-get install -y spamassassin

# Rsyslog
RUN apt-get install -y rsyslog

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 25 587 465
EXPOSE 143 993

#COPY conf/x /etc/x

COPY init/start /usr/local/bin/start
COPY init/servstart /usr/local/bin/servstart
COPY init/servstop /usr/local/bin/servstop
COPY init/copyetc /usr/local/bin/copyetc
COPY init/mailbackup /usr/local/bin/mailbackup
COPY init/mailrestore /usr/local/bin/mailrestore
COPY init/usernew /usr/local/bin/usernew
COPY init/userdel /usr/local/bin/userdel

RUN chmod +x /usr/local/bin/start
RUN chmod +x /usr/local/bin/servstart
RUN chmod +x /usr/local/bin/servstop
RUN chmod +x /usr/local/bin/copyetc
RUN chmod +x /usr/local/bin/mailbackup
RUN chmod +x /usr/local/bin/mailrestore
RUN chmod +x /usr/local/bin/usernew
RUN chmod +x /usr/local/bin/userdel

RUN mkdir /home/backupmail
RUN chmod 777 /home/backupmail
RUN mkdir /home/backupetc
RUN /usr/local/bin/copyetc

ENTRYPOINT ["/usr/local/bin/start"]

#
