#!/bin/bash

n=`pwd | awk 'BEGIN {FS="/"};{printf $NF }'`
p=`pwd`

if [ -d $(pwd)/backup ]; then
	echo Backup rendben.
else
	mkdir $(pwd)/backup
	chmod 777 $(pwd)/backup
	echo Backup rendben.
fi

podman exec "$n" /usr/local/bin/mailbackup
echo Levelezés mentése: rendben.

d=`date +"%y%m%d"`
#echo $d

b=$(pwd)/backup
cd $(pwd)/backupmail
for i in *.tar.gz; do
	mv $i $b/$d-$i
	echo $d-$i
done

cd $p

#
