#!/bin/bash

d=`pwd`
cd ..

n=`pwd | awk 'BEGIN {FS="/"};{printf $NF }'`
p=`sudo podman ps | grep "$n" | awk 'BEGIN {FS=" "};{print $1}'`

if [ ! -z "$1" ]; then
	podman container cp $1 "$n":/home
else
	echo Nincs megadva másolandó fájl.
fi

cd $d

#
