FROM debian

MAINTAINER peter version: 0.1

RUN apt-get update

# Apache2
RUN apt-get install -y apache2
RUN apt-get install -y mc
RUN apt-get install -y aptitude

# PHP
RUN apt-get install -y libapache2-mod-php
RUN apt-get install -y php-mysql

# PhpMyAdmin
#RUN apt-get install -y phpmyadmin

# Web browser
RUN apt-get install -y lynx

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN a2enmod php7.3
RUN a2enmod ssl

COPY conf/80.conf /etc/apache2/sites-enabled/80.conf
COPY conf/443.conf /etc/apache2/sites-enabled/443.conf
COPY conf/.htpasswd /etc/apache2/.htpasswd

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

EXPOSE 80 443

COPY init/start /usr/local/bin/start
COPY init/servstart /usr/local/bin/servstart
COPY init/servstop /usr/local/bin/servstop
COPY init/addapacheuser /usr/local/bin/addapacheuser

RUN chmod +x /usr/local/bin/start
RUN chmod +x /usr/local/bin/servstart
RUN chmod +x /usr/local/bin/servstop
RUN chmod +x /usr/local/bin/addapacheuser

ENTRYPOINT ["/usr/local/bin/start"]

#CMD ["/bin/bash"]
