#!/bin/sh

if [ ! -f /etc/postfix/main.cf ]; then
	cp -r /home/backupetc/etc/postfix/* /etc/postfix
fi
if [ ! -f /etc/dovecot/dovecot.conf ]; then
	cp -r /home/backupetc/etc/dovecot/* /etc/dovecot
fi
if [ ! -f /etc/spamassassin/local.cf ]; then
	cp -r /home/backupetc/etc/spamassassin/* /etc/spamassassin
fi
if [ ! -f /etc/amavis/conf.d/01-debian ]; then
	cp -r /home/backupetc/etc/amavis/* /etc/amavis
fi

adduser clamav amavis
echo "example.com" > /etc/mailname

service rsyslog start

freshclam

service clamav-daemon start
service clamav-freshclam start
service spamassassin start
service amavis start
service postfix start
service dovecot start

touch /var/log/lastlog
tail -f /var/log/lastlog

#
