#!/bin/bash

IMAGE="savedcont"
USER="peter"

p=`pwd`
cd ..

n=`pwd | awk 'BEGIN {FS="/"};{printf $NF }'`

if [ -f "/home/$USER/$IMAGE" ]; then
    mv "/home/$USER/$IMAGE" ./$IMAGE
    sudo podman import $IMAGE $n
    #sudo rm $IMAGE
else
    echo "?? $IMAGE ??"
fi

cd $p

#
