FROM debian

MAINTAINER peter version: 0.1

RUN apt-get update

# Mariadb
RUN apt-get install -y mariadb-server
RUN apt-get install -y mariadb-client
RUN apt-get install -y mc

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 3306

COPY init/start.sh /usr/local/bin/start.sh
COPY init/sqlinit.sh /usr/local/bin/sqlinit.sh
COPY init/conf.sql /usr/local/bin/conf.sql
COPY init/sqlbackup.sh /usr/local/bin/sqlbackup.sh
COPY init/sqlrestore.sh /usr/local/bin/sqlrestore.sh

RUN chmod +x /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/sqlinit.sh
RUN chmod +x /usr/local/bin/sqlbackup.sh
RUN chmod +x /usr/local/bin/sqlrestore.sh

COPY conf/server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

ENTRYPOINT ["/usr/local/bin/start.sh"]

#CMD ["/bin/bash"]
