FROM debian

MAINTAINER peter version: 0.1

RUN apt-get update

# Mariadb
RUN apt-get install -y mariadb-server
RUN apt-get install -y mariadb-client
RUN apt-get install -y mc

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /run/mysqld
RUN chmod 777 /run/mysqld

EXPOSE 3306

COPY init/start /usr/local/bin/start
COPY init/servstart /usr/local/bin/servstart
COPY init/servstop /usr/local/bin/servstop
COPY init/sqlinit /usr/local/bin/sqlinit
COPY init/conf.sql /usr/local/bin/conf.sql
COPY init/sqlbackup /usr/local/bin/sqlbackup
COPY init/sqlrestore /usr/local/bin/sqlrestore

RUN chmod +x /usr/local/bin/start
RUN chmod +x /usr/local/bin/servstart
RUN chmod +x /usr/local/bin/servstop
RUN chmod +x /usr/local/bin/sqlinit
RUN chmod +x /usr/local/bin/sqlbackup
RUN chmod +x /usr/local/bin/sqlrestore

COPY conf/server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Budapest /etc/localtime

ENTRYPOINT ["/usr/local/bin/start"]

#CMD ["/bin/bash"]
